### ISSUE TITLE
宿主资源id问题

### ISSUE THREAD

**Issue by LoliZh** [bunnyblue/ACDDExtension#2]
在ACDDLauncher的res/values/public.xml中改变资源id的值，宿主中R.java的值并没有改成我指定的这个值。是我的aapt有问题还是public.xml中的值需要根据R.java中的id来赋值？

**Comment by bunnyblue** [comment]
这个id的package id应该是7f,各个类型是有区间的

**Comment by LoliZh** [comment]
package id是0x7f，比如原来R.java中的id是0x7f030002，我在public.xml中修改成0x7f030001，R文件中的id还是原来的0002。

**Comment by bunnyblue** [comment]
应该没问题，xml那个drawable没问题啊

**Comment by LoliZh** [comment]
我也是修改public.xml中那个drawable的id来测试，发现R.java中的id并没有改变，是我的aapt有问题吗?我用你给的23下面的aapt以及libc++.dylib替换了buildTools 23.0.1下面的aapt以及libc++。

**Comment by bunnyblue** [comment]
https://code.google.com/p/android/issues/detail?id=200249 可能是studio的bug，生病了，暂时研究不了

**Comment by bunnyblue** [comment]
https://github.com/ceabie/AndroidPublicXmlCompat

**Comment by bunnyblue** [comment]
https://plus.google.com/+ChrisBanes/posts/8Rip6rQGK32
