### ISSUE TITLE
应用安装问题

### ISSUE THREAD

**Issue by dashen19930328** [bunnyblue/ACDDExtension#3]
你好，我想问一下，就是自己写得一个应用，直接调用ACDD里面的Install方法，最近发现安装好后，不能够启动应用，报的错是BundleInfo中没有这个应用的相关信息，给出的demo安装与自己写的应用安装，因为demo的应用信息都会写入Json里面，直接读取，但是应用安装后，会生成文件，读取文件信息来获取应用信息，不知道是不是默认的这个路径在真机里面需要访问权限还是怎样，就是说没有应用信息，所以启动不了，望作者解答，万分感谢

**Comment by bunnyblue** [comment]
有个jar项目下面，脚本运行这个jar就可以了，你看着脚本有没有被注释，那个脚本应该是打包自动运行

**Comment by bunnyblue** [comment]
ref https://code.google.com/p/android/issues/detail?id=219732
