### ISSUE TITLE
How to build plugin module with ACDD?

### ISSUE THREAD

**Issue by Tiny1213** [bunnyblue/ACDDExtension#37]
How to build plugin module with ACDD?Could you provide more details for how to building?

**Comment by bunnyblue** [comment]
https://github.com/bunnyblue/ACDDExtension/tree/master/Samples

**Comment by Tiny1213** [comment]
:HomeLauncher:processAcddDebugAndroidTestResources
ERROR: Unknown option '--ACDD-resoure-id'
Usage:
 aapt l[ist] [-v] [-a] file.{zip,jar,apk}
   List contents of Zip-compatible archive.
 aapt d[ump] [--values] [--include-meta-data] WHAT file.{apk} [asset [asset ...]]
   strings          Print the contents of the resource table string pool in the APK.
   badging          Print the label and icon for the app declared in APK.
   permissions      Print the permissions from the APK.
   resources        Print the resource table from the APK.
   configurations   Print the configurations in the APK.
   xmltree          Print the compiled xmls in the given assets.
   xmlstrings       Print the strings of the given compiled xml assets.

我clone下来之后，make HomeLauncher，会失败，还有啊，ACDD里的BuildTools目录里的有什么用？

**Comment by bunnyblue** [comment]
使用tool 23 看下你放对了没

**Comment by Tiny1213** [comment]
研究了一下午，现在可以了，3Q

**Comment by Tiny1213** [comment]
hi，有以下问题请教下
1请问插件module能不能调用宿主service里的public方法？
我试了，调用方法的时候报错，
Failed to find the bundle in BundleInfoList for component org.acdd.launcher.BootService

2宿主和插件之间module类，是不是不能用parceable去序列化传递数据？
再反序列化的时候报错，
Class not found when unmarshalling: org.acdd.launcher.module.IModule
3宿主和插件之间能不能用广播通信？

**Comment by bunnyblue** [comment]
1 第一个这个你的调用有问题应该，不知道你怎么调用的接口看你的log是调用问题
2 应该可以IModule在宿主里面吗？在插件里面？
3 通信没问题啊。以前测试过OTTO

**Comment by Tiny1213** [comment]
hi，我又来了
1，3问题解决了，是可以的。
2的问题反序列话不行啊-。-，
![image](https://cloud.githubusercontent.com/assets/9071200/11161922/d60d3168-8ac5-11e5-9eab-0587be7b8226.png)
![image](https://cloud.githubusercontent.com/assets/9071200/11161924/e115610c-8ac5-11e5-80c2-99bacd6fc18c.png)

![image](https://cloud.githubusercontent.com/assets/9071200/11161926/fdf28dd6-8ac5-11e5-94a1-32e52e9b81ba.png)
好像是那个静态的 CREATOR找不到？你试过可以么？

**Comment by bunnyblue** [comment]
你的CREATOR在宿主里面还是在插件里面？

**Comment by Tiny1213** [comment]
IModule是在宿主项目里的，我把java文件编译成一个class.jar，插件项目依赖这个jar，编译时候就ok了。这样可以么？
dependencies {
    provided files('libs/ACDDHost.jar')
}

**Comment by bunnyblue** [comment]
应该没问题，如果找不到Class的话回到宿主的classloader搜索

**Comment by bunnyblue** [comment]
更新了 再试下

**Comment by Tiny1213** [comment]
It works！Thank you

**Comment by Tiny1213** [comment]
hi，请问资源名是不是不能有重复的？插件与宿主之间，插件与插件之间？

**Comment by bunnyblue** [comment]
资源名可以重复，主要是定义的package-id不能重复

**Comment by Tiny1213** [comment]
productFlavors {
        acdd {
            aaptOptions.additionalParameters '--ACDD-resoure-id', '0x6b', '--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()
        }
        normal {
        }
    }
resource-id  0x6b 插件这个id有什么要求？插件的id能一样么？

**Comment by bunnyblue** [comment]
id 看wiki 有范围，0x20-0x7e之间， id不能一样。一样的话可能会出现资源混乱

**Comment by Tiny1213** [comment]
![image](https://cloud.githubusercontent.com/assets/9071200/11162654/61a1fd82-8ae7-11e5-945a-d55ec9d582cd.png)
这个么？0x02~0x7e之间的么

**Comment by bunnyblue** [comment]
0x20--x7f

**Comment by Tiny1213** [comment]
hi，我有个问题解决不了。
我是plugin module 用的support包，activity是AppCompatActivity子类，必须用Theme.Compat的主题
support包里有个检查，
![image](https://cloud.githubusercontent.com/assets/9071200/11176222/e61025d2-8c75-11e5-9722-32631576643e.png)
plugin的activity会在这里抛出异常。
这里我觉得这个检查应该能通过的。
![image](https://cloud.githubusercontent.com/assets/9071200/11176265/32475d58-8c76-11e5-97de-576c218cca27.png)
我尝试用plugin里的主题，在activity的onCreate里设置主题资源，但还是不行

如果用宿主mainfest文件里注册activity时的主题也不能通过检查。

**Comment by bunnyblue** [comment]
对于theme 宿主注册，使用public 的方式导出定义，然后宿主定义，你的插件只能provided AppCompat的jar  资源的话使用public导出用。集成的话 这样

**Comment by Tiny1213** [comment]
SecurityBundleListner.PUBLIC_KEY 是用来校验什么东西的？现在会提示Public Key error，PLZ update your  public key，然后杀死当前进程。

**Comment by bunnyblue** [comment]
检测插件的签名，可能有bug，你可以关掉。后面看下

**Comment by Tiny1213** [comment]
![image](https://cloud.githubusercontent.com/assets/9071200/11177769/f51bc2cc-8c82-11e5-8d80-c23bb7ce7147.png)
![image](https://cloud.githubusercontent.com/assets/9071200/11177794/14ac9684-8c83-11e5-8e5e-52deefb3fe63.png)

activity只有setTheme 这一个api可以用，我能想到就上面这样的方法，不过貌似不行啊。
因为setTheme后，plugin的activity还是在当前资源id路径里找到，并不能找到宿主的资源中的theme啊。
是这样处理么？

**Comment by bunnyblue** [comment]
activity注册，theme在宿主里面注册，以前测过，没问题

**Comment by Tiny1213** [comment]
如果是普通的activity和主题的话是可以的，但是如果是继承的是support包里的AppcompatActivity，这个activity必须要用Theme.AppCompat.XXX的主题，有硬性检查。我觉得可能是因为plugin中我是compile的scope去以来 support-V7包，导致编译出来的apk里会有一套plugin的support包里的class和资源id，和宿主的起冲突了。但如果只依赖jar包，编译的时候无法访问资源啊，这个没找到解决办法。

**Comment by bunnyblue** [comment]
编译的时候使用'--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()。具体写法看sdk

**Comment by Tiny1213** [comment]
我plugin依赖jar包的类，主题用宿主mainfest里的，这样可以，但是jar包里没资源，plugin在编码的时候不能访问support包里，有办法解决么？
--ACDD-shared-resources', rootProject.file("public.xml").getAbsolutePath()  ，这句我就没看懂。。。

**Comment by bunnyblue** [comment]
你看下脚本，里面有搜下

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by Tiny1213** [comment]
看不懂了0.0

**Comment by Tiny1213** [comment]
请问build Tool 22的aapt应该也可以用的吧？

**Comment by bunnyblue** [comment]
aapt已经让我移除掉了。如果旧版本的话可以，新版本修改了参数，使用23.没在测试低版本，有空上传下23的补丁

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by Tiny1213** [comment]
难道不需要替换sdk里的aapt也能编译么？不然为啥移除，因为23的sdk里没有httpClient的类了，我只能用22的编译

**Comment by bunnyblue** [comment]
需要替换。维护好几套代码太费劲了23，支持共享资源，22没做适配，22在仓库里面还有，你到tag里面看下以前的版本，还有 22和23的结构不太一样。
23
```
android {
    useLibrary 'org.apache.http.legacy'
```
这样也可以，或者用以前的版本

**Comment by Tiny1213** [comment]
可以了

**Comment by Tiny1213** [comment]
我注意到ACDD Core在运行的时候，会去加载.so库，这个一定要放到宿主module里么？我没放进去也没发现什么问题。

**Comment by bunnyblue** [comment]
你是说dexopt这个吧？这个预处理dex只是，你不用也没关系，可能慢一点而已。这个放组件用不到的
