### ISSUE TITLE
貌似ACDD不支持Plugin app的package以cn开头的？只支持com开头的？

### ISSUE THREAD

**Issue by DavidYes** [bunnyblue/ACDDExtension#38]
看了有部分代码，貌似ACDD只是写死用libcom开头搜寻插件so文件？求证！比如cn.acdd.qrcode就无法找出来。实际测试下来也是如此。

**Comment by bunnyblue** [comment]
恩 是写死的，一般包名都是com开头的，所以当初没考虑这个，后面看看，那这样可能还有org什么的，头疼

**Comment by DavidYes** [comment]
我如果在插件app中的layout定义了  
   <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
及时主app和插件app都用同一个android_support_v4.jar来编译，也会出现

**Comment by DavidYes** [comment]
11-18 18:25:53.301 18917-18917/org.acdd.launcher E/SQLiteLog: (10) Failed to do file read, got: 0, amt: 100, last Errno: 2
11-18 18:25:53.780 18917-18917/org.acdd.launcher W/InputMethodManager: startInputInner : InputBindResult == null
11-18 18:25:54.122 18917-18917/org.acdd.launcher W/System.err: java.lang.ClassCastException: android.support.v4.view.ViewPager cannot be cast to android.support.v4.view.ViewPager
11-18 18:25:54.124 18917-18917/org.acdd.launcher W/System.err:     at com.cienet.android.campuscard.CairdGuideActivity.onCreate(Unknown Source)
11-18 18:25:54.124 18917-18917/org.acdd.launcher W/System.err:     at android.app.Activity.performCreate(Activity.java:5122)
11-18 18:25:54.124 18917-18917/org.acdd.launcher W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
11-18 18:25:54.124 18917-18917/org.acdd.launcher W/System.err:     at org.acdd.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:523)
11-18 18:25:54.125 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
11-18 18:25:54.125 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
11-18 18:25:54.125 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:165)
11-18 18:25:54.125 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
11-18 18:25:54.125 18917-18917/org.acdd.launcher W/System.err:     at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:193)
11-18 18:25:54.125 18917-18917/org.acdd.launcher W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
11-18 18:25:54.126 18917-18917/org.acdd.launcher W/System.err:     at android.os.Looper.loop(Looper.java:194)
11-18 18:25:54.126 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5391)
11-18 18:25:54.126 18917-18917/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-18 18:25:54.126 18917-18917/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
11-18 18:25:54.126 18917-18917/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
11-18 18:25:54.126 18917-18917/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
11-18 18:25:54.126 18917-18917/org.acdd.launcher W/System.err:     at dalvik.system.NativeStart.main(Native Method)
11-18 18:25:54.128 18917-18917/org.acdd.launcher W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.acdd.launcher/com.cienet.android.campuscard.CairdGuideActivity}: java.lang.RuntimeException: (1)Paths in ContextThemeWrapper_mResources:[/system/framework/framework-res.apk, /system/framework/mediatek-res.apk, /data/app/org.acdd.launcher-1.apk, /data/data/org.acdd.launcher/lib/libcom_acdd_homelauncher.so, /data/data/org.acdd.launcher/lib/libcom_acdd_qrcode.so, /data/data/org.acdd.launcher/lib/libcom_bestpay_creditcard.so, /data/data/org.acdd.launcher/lib/libcom_chinatelecom_bestfacepay.so, /data/data/org.acdd.launcher/lib/libcom_cienet_android_campuscard.so] paths in runtime:newDelegateResources [/data/app/org.acdd.launcher-1.apk,/data/data/org.acdd.launcher/lib/libcom_acdd_homelauncher.so,/data/data/org.acdd.launcher/lib/libcom_acdd_qrcode.so,/data/data/org.acdd.launcher/lib/libcom_bestpay_creditcard.so,/data/data/org.acdd.launcher/lib/libcom_chinatelecom_bestfacepay.so,/data/data/org.acdd.launcher/lib/libcom_cienet_android_campuscard.so,]
11-18 18:25:54.128 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2351)
11-18 18:25:54.129 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
11-18 18:25:54.129 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:165)
11-18 18:25:54.130 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
11-18 18:25:54.130 18917-18917/org.acdd.launcher W/System.err:     at org.acdd.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:193)
11-18 18:25:54.130 18917-18917/org.acdd.launcher W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
11-18 18:25:54.131 18917-18917/org.acdd.launcher W/System.err:     at android.os.Looper.loop(Looper.java:194)
11-18 18:25:54.138 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5391)
11-18 18:25:54.140 18917-18917/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-18 18:25:54.141 18917-18917/org.acdd.launcher W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
11-18 18:25:54.142 18917-18917/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
11-18 18:25:54.142 18917-18917/org.acdd.launcher W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
11-18 18:25:54.144 18917-18917/org.acdd.launcher W/System.err:     at dalvik.system.NativeStart.main(Native Method)
11-18 18:25:54.145 18917-18917/org.acdd.launcher W/System.err: Caused by: java.lang.RuntimeException: (1)Paths in ContextThemeWrapper_mResources:[/system/framework/framework-res.apk, /system/framework/mediatek-res.apk, /data/app/org.acdd.launcher-1.apk, /data/data/org.acdd.launcher/lib/libcom_acdd_homelauncher.so, /data/data/org.acdd.launcher/lib/libcom_acdd_qrcode.so, /data/data/org.acdd.launcher/lib/libcom_bestpay_creditcard.so, /data/data/org.acdd.launcher/lib/libcom_chinatelecom_bestfacepay.so, /data/data/org.acdd.launcher/lib/libcom_cienet_android_campuscard.so] paths in runtime:newDelegateResources [/data/app/org.acdd.launcher-1.apk,/data/data/org.acdd.launcher/lib/libcom_acdd_homelauncher.so,/data/data/org.acdd.launcher/lib/libcom_acdd_qrcode.so,/data/data/org.acdd.launcher/lib/libcom_bestpay_creditcard.so,/data/data/org.acdd.launcher/lib/libcom_chinatelecom_bestfacepay.so,/data/data/org.acdd.launcher/lib/libcom_cienet_android_campuscard.so,]
11-18 18:25:54.147 18917-18917/org.acdd.launcher W/System.err:     at org.acdd.runtime.InstrumentationHook.HandleResourceNotFound(InstrumentationHook.java:301)
11-18 18:25:54.147 18917-18917/org.acdd.launcher W/System.err:     at org.acdd.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:530)
11-18 18:25:54.147 18917-18917/org.acdd.launcher W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
11-18 18:25:54.149 18917-18917/org.acdd.launcher W/System.err: 	... 12 more
11-18 18:25:54.150 18917-18917/org.acdd.launcher W/System.err: Caused by: java.lang.ClassCastException: android.support.v4.view.ViewPager cannot be cast to android.support.v4.view.ViewPager
11-18 18:25:54.151 18917-18917/org.acdd.launcher W/System.err:     at com.cienet.android.campuscard.CairdGuideActivity.onCreate(Unknown Source)
11-18 18:25:54.153 18917-18917/org.acdd.launcher W/System.err:     at android.app.Activity.performCreate(Activity.java:5122)
11-18 18:25:54.155 18917-18917/org.acdd.launcher W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
11-18 18:25:54.155 18917-18917/org.acdd.launcher W/System.err:     at org.acdd.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:523)
11-18 18:25:54.155 18917-18917/org.acdd.launcher W/System.err: 	... 13 more
11-18 18:25:54.564 18917-19305/org.acdd.launcher W/System.err: java.net.SocketException: failed to connect to /192.178.106.81 (port 8081) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
11-18 18:25:54.568 18917-19305/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:256)
11-18 18:25:54.568 18917-19305/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:178)
11-18 18:25:54.568 18917-19305/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:112)
11-18 18:25:54.568 18917-19305/org.acdd.launcher W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
11-18 18:25:54.568 18917-19305/org.acdd.launcher W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
11-18 18:25:54.568 18917-19305/org.acdd.launcher W/System.err:     at java.net.Socket.connect(Socket.java:860)
11-18 18:25:54.569 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
11-18 18:25:54.569 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
11-18 18:25:54.570 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
11-18 18:25:54.570 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
11-18 18:25:54.571 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
11-18 18:25:54.573 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
11-18 18:25:54.573 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
11-18 18:25:54.574 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
11-18 18:25:54.574 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
11-18 18:25:54.575 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
11-18 18:25:54.575 18917-19305/org.acdd.launcher W/System.err:     at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:205)
11-18 18:25:54.580 18917-19305/org.acdd.launcher W/System.err:     at com.cienet.android.campuscard.a.a.a.a(Unknown Source)
11-18 18:25:54.580 18917-19305/org.acdd.launcher W/System.err:     at com.cienet.android.campuscard.a.a.c.run(Unknown Source)
11-18 18:25:54.580 18917-19305/org.acdd.launcher W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-18 18:25:54.580 18917-19305/org.acdd.launcher W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-18 18:25:54.582 18917-19305/org.acdd.launcher W/System.err:     at java.lang.Thread.run(Thread.java:838)
11-18 18:25:54.583 18917-19305/org.acdd.launcher W/System.err: Caused by: libcore.io.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
11-18 18:25:54.586 18917-19305/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:234)
11-18 18:25:54.588 18917-19305/org.acdd.launcher W/System.err: 	... 21 more
11-18 18:25:54.590 18917-19305/org.acdd.launcher E/error: CCBPHttpManager.ACTION_RESPONSE_ERROR
11-18 18:25:57.559 18917-19304/org.acdd.launcher W/System.err: java.net.SocketException: failed to connect to /192.178.106.81 (port 8081) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
11-18 18:25:57.560 18917-19304/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:256)
11-18 18:25:57.560 18917-19304/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:178)
11-18 18:25:57.561 18917-19304/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:112)
11-18 18:25:57.561 18917-19304/org.acdd.launcher W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
11-18 18:25:57.561 18917-19304/org.acdd.launcher W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
11-18 18:25:57.561 18917-19304/org.acdd.launcher W/System.err:     at java.net.Socket.connect(Socket.java:860)
11-18 18:25:57.562 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
11-18 18:25:57.563 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
11-18 18:25:57.564 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
11-18 18:25:57.564 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
11-18 18:25:57.565 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
11-18 18:25:57.565 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
11-18 18:25:57.565 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
11-18 18:25:57.566 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
11-18 18:25:57.566 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
11-18 18:25:57.566 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
11-18 18:25:57.567 18917-19304/org.acdd.launcher W/System.err:     at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:205)
11-18 18:25:57.567 18917-19304/org.acdd.launcher W/System.err:     at com.cienet.android.campuscard.a.a.a.a(Unknown Source)
11-18 18:25:57.568 18917-19304/org.acdd.launcher W/System.err:     at com.cienet.android.campuscard.a.a.c.run(Unknown Source)
11-18 18:25:57.569 18917-19304/org.acdd.launcher W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-18 18:25:57.569 18917-19304/org.acdd.launcher W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-18 18:25:57.569 18917-19304/org.acdd.launcher W/System.err:     at java.lang.Thread.run(Thread.java:838)
11-18 18:25:57.572 18917-19304/org.acdd.launcher W/System.err: Caused by: libcore.io.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
11-18 18:25:57.576 18917-19304/org.acdd.launcher W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:234)
11-18 18:25:57.577 18917-19304/org.acdd.launcher W/System.err: 	... 21 more
11-18 18:25:57.578 18917-19304/org.acdd.launcher E/error: CCBPHttpManager.ACTION_RESPONSE_ERROR

**Comment by DavidYes** [comment]
导致anr错误，但是奇怪的时候，第二次再进入的时候，就不会出现anr，而是可以正常访问调用插件app

**Comment by DavidYes** [comment]
谢谢 bunnyblue 的快速反应！赞！

**Comment by DavidYes** [comment]
请问，ACDD这套架构，有在阿里的产品中商用吗？查看了 支付宝，发现apk有42M多，看上去像是hybrid架构，没用动态加载？

**Comment by bunnyblue** [comment]
你不应该把相同的代码编译进去，我不是阿里的，再次声明，也没跟阿里有啥交集

**Comment by DavidYes** [comment]
Sorry，误解了曾经的阿里人之前推荐ACDD时候的意思了。“你不应该把相同的代码编译进去?”你的意思是宿主和插件app要一起编译 避免 11-18 18:25:54.150 18917-18917/org.acdd.launcher W/System.err: Caused by: java.lang.ClassCastException: android.support.v4.view.ViewPager cannot be cast to android.support.v4.view.ViewPager ？不是很明白。另外，插件包.com;.org;.cn开头能扩展支持到吗？

**Comment by bunnyblue** [comment]
@DavidYes  cn能支持，等周末或者自己修改下就好了，你应该吧support-v4编译到宿主里面了，插件里面也有一份，两个不在一个classloader中，转型肯定或出现类型转换异常了，插件中得support用provided方式编译，不知道你怎么处理的

**Comment by DavidYes** [comment]
@Bunnyblue, 我自己在BundlesInstall的process()函数中将写实的libcom字符串做了点优化处理，目前还不够智能，想着是遍历 ACDDConfig.PRELOAD_DIR目录，或者是能够借鉴apk转so重命名时候的机制。后续如果成熟了，再贴上来，目前对这套机制不是很了解，希望能够一直学习，ACDD能够稳定起来上线推广。

**Comment by bunnyblue** [comment]
这样可以，你先自己弄着呗，如果不错的话可以pull，周末我看看把cn的加上

**Comment by bunnyblue** [comment]
https://github.com/bunnyblue/ACDD/commit/e40aa7524265db2626a60ba7be2ce9f2064f62cf
