### ISSUE TITLE
应用的重复安装问题

### ISSUE THREAD

**Issue by dashen19930328** [bunnyblue/ACDDExtension#4]
你好，我现在自己手写一个demo程序，第一次安装启动没有问题，但是uninstall，重新启动后，在install发现启动不了，因为没有生成bundle.zip？这是在真机上，在本地是模拟器上好像是没有问题的，请问这是什么问题导致的？另外我想问作者你，这是可以实现四大组件免注册的吧，将这个开源工程做成应用应该也是可行的吗？希望你百忙之中予以解答，不甚感激

**Comment by bunnyblue** [comment]
在install发现启动不了 ,debug app better

四大组件免注册  support activity  and service now,enable stub mode
将这个开源工程做成应用 yes,you can
