### ISSUE TITLE
为何现在没有aapt的源码了？

### ISSUE THREAD

**Issue by out0fmemory** [bunnyblue/ACDDExtension#41]
为何现在没有aapt的源码了？想看下实现原理，但master里已经被删除了

**Comment by bunnyblue** [comment]
有，你从release里面下载就可以不了，最后一个版本

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by out0fmemory** [comment]
thks，刚才看commit历史找到了，只是国内的环境，github都卡个半死，找commit麻烦
