### ISSUE TITLE
Is there aappt source code?

### ISSUE THREAD

**Issue by mahuafactory** [bunnyblue/ACDDExtension#44]

**Comment by bunnyblue** [comment]
看下历史，在以前

**Comment by mahuafactory** [comment]
这个库支持动态下载，并加载插件吗，用户点击某个模块之后，下载并加载这个模块

**Comment by bunnyblue** [comment]
支持

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*


2016-01-28 20:02 GMT+08:00 mahuafactory <notifications@github.com>:
