### ISSUE TITLE
怎么编译？aapt要换？

### ISSUE THREAD

**Issue by liuguangli** [bunnyblue/ACDDExtension#45]
宿主工程和插件工程分别怎么编译？aapt要换？

**Comment by bunnyblue** [comment]
宿主没关系，插件需要替换aapt，你看下wiki里面有

**Comment by rainmeterLotus** [comment]
哪来的wiki啊？

**Comment by hejie** [comment]
Error:Execution failed for task ':AppCenter:processAcddDebugAndroidTestResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/opt/android-sdk-linux/build-tools/23.0.2/aapt'' finished with non-zero exit value 127

**Comment by hejie** [comment]
linux 环境下报错
Error:Execution failed for task ':AppCenter:processAcddDebugAndroidTestResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/opt/android-sdk-linux/build-tools/23.0.2/aapt'' finished with non-zero exit value 127
