### ISSUE TITLE
appt提供的mac的x86 c++链接库不能替换

### ISSUE THREAD

**Issue by lucifdch** [bunnyblue/ACDDExtension#47]
如题，替换后电脑重启，提示uuid校验失败，最后重装系统解决。。。希望还是在文档里提醒一下其他同人别干了我这样的蠢事。。。

**Comment by bunnyblue** [comment]
替换的哪儿的？

**Comment by lucifdch** [comment]
ACDDExtension/buildTools/binary/build.tool.R23/darwin-x86/lib64/libc++.dylib 替换系统的/usr/lib/libc++.dylib。

**Comment by bunnyblue** [comment]
很明显你不能这样做啊，这个位于android sdk下面的 ，这个跟系统的没啥关系
